description: Runs schedule

inputs:
  token:
    description: Personal Access Token
    required: false
    default: ${{ github.token }}

runs:
  using: composite

  steps:
    - uses: m1nk6o5e-t7ue/ak3io8z@checkout-branch
      with:
        token: ${{ inputs.token }}


    - uses: m1nk6o5e-t7ue/ak3io8z@user-action
    - uses: m1nk6o5e-t7ue/ak3io8z@keep-alive
