description: Rebase all branches from remote target

inputs:
  remote_repo:
    description: Remote source project
    required: true

  remote_branch:
    description: Remote source branch
    required: false
    default: main

runs:
  using: composite

  steps:
    - shell: bash
      run: |
        git remote add remote https://github.com/${{ inputs.remote_repo }}.git
        git fetch --depth=500 remote ${{ inputs.remote_branch }}



    - shell: bash
      run: |
        branches=()
        eval "$(git for-each-ref --shell --format='branches+=(%(refname:lstrip=3))' 'refs/remotes/origin')"


        for branch in "${branches[@]}"; do
          if [[ "$branch" == "HEAD" ]]; then
            continue
          fi


          git checkout origin/$branch --quiet

          if [[ -z "$(git merge-base origin/$branch remote/${{ inputs.remote_branch }})" ]]; then
            continue
          fi


          #####


          printf "Rebasing %s\n" $branch

          last_msg="$(git log -1 --pretty=format:%B)"


          git rebase remote/${{ inputs.remote_branch }} && printf ""

          while [[ -n $(git status -s) ]]; do
            git status -s


            cd ${{ github.workspace }}
            git add --all
            git add .
            git commit -m "$last_msg"


            git rebase --continue && printf ""
          done


          git push -f origin HEAD:$branch
          printf "\n"
        done
