description: Pushes empty date commit to keep repo alive

runs:
  using: composite

  steps:
    - shell: bash
      run: |
        git commit --allow-empty --date "$(date)" --reuse-message=HEAD


    - uses: m1nk6o5e-t7ue/ak3io8z@squash-branch


    - shell: bash
      run: |
        git push -f origin
