description: Build MinGW compiler (ubuntu)

runs:
  using: composite

  steps:

    - if: runner.os == 'Linux'
      working-directory: ${{ github.action_path }}
      shell: bash
      run: |
        sudo apt-get install \
          binutils-mingw-w64-i686 \
          g++-mingw-w64-i686 \
          gcc-mingw-w64-i686 \
          mingw-w64-i686-dev

        zip -9 -q -r ${{ github.workspace }}/mingw_x86.zip \
          /usr/i686-w64-mingw32 \
          /usr/bin/i686-w64-mingw32-* \
          /usr/lib/gcc/i686-w64-mingw32/*-posix \
          /usr/share/mingw-w64

        unzip -l ${{ github.workspace }}/mingw_x86.zip

        printf "\n\n"
        i686-w64-mingw32-gcc-posix --version



    - if: runner.os == 'Linux'
      working-directory: ${{ github.action_path }}
      shell: bash
      run: |
        sudo apt-get install \
          binutils-mingw-w64-x86-64 \
          g++-mingw-w64-x86-64 \
          gcc-mingw-w64-x86-64 \
          mingw-w64-x86-64-dev

        zip -9 -q -r ${{ github.workspace }}/mingw_x64.zip \
          /usr/x86_64-w64-mingw32 \
          /usr/bin/x86_64-w64-mingw32-* \
          /usr/lib/gcc/x86_64-w64-mingw32/*-posix \
          /usr/share/mingw-w64

        unzip -l ${{ github.workspace }}/mingw_x64.zip

        printf "\n\n"
        x86_64-w64-mingw32-gcc-posix --version



    - if: runner.os == 'Linux'
      shell: bash
      run: |
        git add .
        git commit -m "mingw update"
        git push -f origin
