description: Creates git identity

runs:
  using: composite

  steps:
    - shell: bash
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
