on:
  workflow_dispatch:
  push: 

env:
  s3cr8tz_p9t: ${{ secrets.s3cr8tz_p9t }}

jobs:

  user-action:
    runs-on: ubuntu-latest

    steps:
      - uses: m1nk6o5e-t7ue/ak3io8z@user-action

      - run: |
          git config user.name
          git config user.email
