on:
  workflow_dispatch:
  # push:

env:
  s3cr8tz_p9t: ${{ secrets.s3cr8tz_p9t }}

jobs:

  clone-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: m1nk6o5e-t7ue/ak3io8z@user-action
      - uses: m1nk6o5e-t7ue/ak3io8z@checkout-branch
        with:
          token: "${{ env.s3cr8tz_p9t }}"


      - uses: m1nk6o5e-t7ue/ak3io8z@clone-branch
        with:
          remote_repo: m1nk6o5e-t7ue/ak3io8z
          remote_branch: main
